if (NOT SFML_FOUND)
    include(FetchContent)
    message("Declaring SFML...")
    FetchContent_Declare(SFML GIT_REPOSITORY https://github.com/SFML/SFML.git GIT_TAG 2.6.x)
    message("Getting SFML properties...")
    FetchContent_GetProperties(SFML)
    if (NOT SFML_POPULATED)
        message("Populating SFML...")
        FetchContent_Populate(SFML)
        set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        add_subdirectory(${sfml_SOURCE_DIR} ${sfml_BINARY_DIR})
        set(SFML_FOUND TRUE)
    endif()
endif()

message("Fetching SFML...")
FetchContent_MakeAvailable(SFML)
