set(Boost_USE_STATIC_LIBS ON)

if (NOT Boost_FOUND)
    include(FetchContent)
    message("Declaring Boost...")
    FetchContent_Declare(Boost GIT_REPOSITORY https://github.com/boostorg/boost.git GIT_TAG boost-1.80.0)
    message("Getting Boost properties...")
    FetchContent_GetProperties(Boost)
    if (NOT Boost_POPULATED)
        message("Populating boost...")
        FetchContent_Populate(Boost)
        set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        message("Building boost...")
        add_subdirectory(${boost_SOURCE_DIR} ${boost_BINARY_DIR})
        set(Boost_FOUND TRUE)
    endif()
endif()

message("Make Avaialable boost...")
FetchContent_MakeAvailable(Boost)
