if (NOT spdlog_FOUND)
    include(FetchContent)
    message("Declaring spdlog...")
    FetchContent_Declare(spdlog GIT_REPOSITORY https://github.com/gabime/spdlog.git GIT_TAG v1.10.0)
    message("Getting spdlog properties...")
    FetchContent_GetProperties(spdlog)
    if (NOT spdlog_POPULATED)
        message("Populating spdlog...")
        FetchContent_Populate(spdlog)
        set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        add_subdirectory(${spdlog_SOURCE_DIR} ${spdlog_BINARY_DIR})
        set(spdlog_FOUND TRUE)
    endif()
endif()

message("Fetching spdlog...")
FetchContent_MakeAvailable(spdlog)
