#pragma once

#define ARCADE_SCREEN_SIZE_X (384.F)
#define ARCADE_SCREEN_SIZE_Y (256.F)

#define ARCADE_SCREEN_VIEW_X (ARCADE_SCREEN_SIZE_X / 2.F)
#define ARCADE_SCREEN_VIEW_Y (ARCADE_SCREEN_SIZE_Y / 2.F)

#define RTYPE_PLAYFIELD_LEFT (0.F)
#define RTYPE_PLAYFIELD_TOP (0.F)
#define RTYPE_PLAYFIELD_WIDTH (ARCADE_SCREEN_SIZE_X)
#define RTYPE_PLAYFIELD_HEIGHT (205.F)
#define RTYPE_PLAYFIELD_RECT(t) (paa::recTo<T>(paa::FloatRect(RTYPE_PLAYFIELD_LEFT, RTYPE_PLAYFIELD_TOP, RTYPE_PLAYFIELD_WIDTH, RTYPE_PLAYFIELD_HEIGHT)))

#define RTYPE_HUD_LEFT (0.F)
#define RTYPE_HUD_TOP (RTYPE_PLAYFIELD_HEIGHT)
#define RTYPE_HUD_HEIGHT (RTYPE_PLAYFIELD_TOP  - ARCADE_SCREEN_SIZE_Y)
#define RTYPE_HUD_WIDTH (ARCADE_SCREEN_SIZE_X)
#define RTYPE_HUD_RECT (paa::recTo<T>(paa::FloatRect(RTYPE_HUD_LEFT, RTYPE_HUD_TOP, RTYPE_HUD_HEIGHT, RTYPE_HUD_WIDTH)))

#define RTYPE_CLAMP(t, v, l, h) \
    std::clamp(static_cast<t>(v), static_cast<t>(l), static_cast<t>(h))
