name: Build

on:
    push:
        branches:
        - dev
        - main
    pull_request:
jobs:
    build-linux:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install gcc-10 g++-10
            sudo apt-get install libstdc++-10-dev
            sudo apt-get install libpthread-stubs0-dev
            sudo apt-get install libgl1-mesa-dev
            sudo apt-get install libx11-dev
            sudo apt-get install libxrandr-dev
            sudo apt-get install libxcursor-dev
            sudo apt-get install libxinerama-dev 
            sudo apt-get install libxi-dev
            sudo apt-get install libfreetype6-dev
            sudo apt-get install libglew1.5-dev
            sudo apt-get install libjpeg8-dev
            sudo apt-get install libsndfile1-dev
            sudo apt-get install libopenal-dev
            sudo apt-get install libudev-dev
        - name: Build
          run: "mkdir build -p"
        - name: Cache deps
          id: build-deps
          uses: actions/cache@v3
          with:
            path: build/_deps
            key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
        - name: Build
          shell: bash
          run: "cd build && cmake -DCMAKE_CXX_COMPILER=g++-10 .. && make -j1 2>&1"
    build-windows:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v2
          - name: Build
            run: |
              if (Test-Path build) {}
              else {
                    New-Item build -ItemType Directory
              }
          - name: Cache deps
            id: build-deps
            uses: actions/cache@v3
            with:
              path: build/_deps
              key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
          - name: Build
            run: |
              ((Get-Content -path .\CMakeLists.txt -Raw) -replace '/MP8','/MP1') | Set-Content -Path .\CMakeLists.txt
              cd build
              cmake ..
              cmake --build .
